os: osx
language: rust
rust: 1.41.0
cache: cargo

after_success:
  if [ ! -z "$TRAVIS_TAG" ]; then
  cargo install cargo-bump && \
  cargo-bump $TRAVIS_TAG && \
  cargo login $CRATES_TOKEN && \
  cargo publish
  fi
