if: tag IS blank

language: rust
rust: 1.43.0
cache: cargo

env:
  global:
    secure: P1r76h3zV3hHkRLTIWKmeRqAb3hOe9r51tqUzTweqUq7TCq89LXtoWlqff/zxtjFOuSZfPaJlRncLl+4bBCB/C+ksBRYyRS3joViazW9ik9aVc6NUmrJEgBvzCxNfeepLNt46VWFYZtAjiripNHdNYXzcB/4lWYCsitU0dcHww3zvhJy04lwl+qCUs+3kJqP3BP/Yt+VQjq5jQbyFVxtX3RyesWCkHf+5q4P+dRJCpUzt6sK9IWxIX/DbuSvN4ip+g0kiSH4udmUB5CsWCAfdwiyfEe4Yw6yeN8/4HphuWIioeqc4whEoClBxUQzYflOeaR76i7LYDLDj+t2EcZbE74SMUHQrfM28Hbi4uNBTVgKnuUyOsTNXDMcB8ALURI3gtQrpPSdfzmhrBqCeXyCpRgjgXwuTH59MSHhqqPYTxbz/gjTSPe0aijV3Hr2mPtS0NjLYP6wvfrArAs3umWke1gKfpvH+DtqP7aiU+mHhbrWP7FDIiKKeV0OGqVCOXHaj0hh9p4IAftuo4lKj1xX8oSsBI6YQOhF+bPOWdrI4KBYiCTFZY3aePx7XmRmjgO9yB8H560A6pkYeTCRaD36aPaxIKa5X15hjeNRXKpPJ/mXJ5gDl6DZnmagdZftIrqqcuejwB8I2Cqz8S5dlQ+o87/pljIdjz5WUNzG95wKL94=

matrix:
  fast_finish: true
  allow_failures: []
  include:
    - name: "MacOS Build"
      os: osx
    - name: "Linux Build"
      os: linux
    - name: "Linting"
      os: linux
      before_install: skip
      install: skip
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
      script:
        - cargo fmt --all -- --check
        - cargo clippy
      before_deploy: skip
      deploy: []


before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in encrypted/id_rsa.enc -out encrypted/id_rsa -d
  - openssl aes-256-cbc -K $encrypted_b2704e9bbe4d_key -iv $encrypted_b2704e9bbe4d_iv -in encrypted/id_rsa.pub.enc -out encrypted/id_rsa.pub -d
  - chmod 0600 encrypted/id_rsa{,.pub}
  - mv encrypted/id_rsa{,.pub} ${HOME}/.ssh/

install: cargo build --release --verbose

script:
  - cargo test --release --workspace --verbose

before_deploy:
  - pushd target/release
  - tar -czvf "bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz" "bitbucket_server_cli"
  - shasum -a 256 "bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz"
  - popd

deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: target/release/bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz
  name: Draft-travis-${TRAVIS_BUILD_NUMBER}
  body: "[Travis build ${TRAVIS_BUILD_NUMBER}](https://travis-ci.org/github/jensim/bitbucket_server_cli/builds/${TRAVIS_BUILD_NUMBER})"
  skip_cleanup: true
  draft: true
  file_glob: true
  on:
    branch: master
    tags: false
