if: tag IS blank

os: linux
dist: bionic
language: rust
cache:
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"
before_cache:
- rm -rf $HOME/.cargo/registry

env:
  global:
  - secure: P1r76h3zV3hHkRLTIWKmeRqAb3hOe9r51tqUzTweqUq7TCq89LXtoWlqff/zxtjFOuSZfPaJlRncLl+4bBCB/C+ksBRYyRS3joViazW9ik9aVc6NUmrJEgBvzCxNfeepLNt46VWFYZtAjiripNHdNYXzcB/4lWYCsitU0dcHww3zvhJy04lwl+qCUs+3kJqP3BP/Yt+VQjq5jQbyFVxtX3RyesWCkHf+5q4P+dRJCpUzt6sK9IWxIX/DbuSvN4ip+g0kiSH4udmUB5CsWCAfdwiyfEe4Yw6yeN8/4HphuWIioeqc4whEoClBxUQzYflOeaR76i7LYDLDj+t2EcZbE74SMUHQrfM28Hbi4uNBTVgKnuUyOsTNXDMcB8ALURI3gtQrpPSdfzmhrBqCeXyCpRgjgXwuTH59MSHhqqPYTxbz/gjTSPe0aijV3Hr2mPtS0NjLYP6wvfrArAs3umWke1gKfpvH+DtqP7aiU+mHhbrWP7FDIiKKeV0OGqVCOXHaj0hh9p4IAftuo4lKj1xX8oSsBI6YQOhF+bPOWdrI4KBYiCTFZY3aePx7XmRmjgO9yB8H560A6pkYeTCRaD36aPaxIKa5X15hjeNRXKpPJ/mXJ5gDl6DZnmagdZftIrqqcuejwB8I2Cqz8S5dlQ+o87/pljIdjz5WUNzG95wKL94=

jobs:
  fast_finish: true
  include:
  - stage: Linux Build
    name: Linux Build
    before_script:
    - cargo install cargo-audit
    - rustup component add rustfmt-preview
    - rustup component add clippy-preview
    script:
    - cargo fmt --all -- --check
    - cargo clippy
    - cargo audit
    - cargo test --release --verbose --lib
    after_deploy:
    - git remote set-url origin git@github.com:jensim/bitbucket_server_cli.git
    - git config --global user.email "builds@travis-ci.com"
    - git config --global user.name "Travis CI"
    - echo "github.com,192.30.253.112 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" > ${HOME}/.ssh/known_hosts
    - git checkout master
    - export GIT_TAG=travis-build-$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d_%H-%M-%S")
    - git tag "$GIT_TAG" -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
    - git push origin $GIT_TAG
  - stage: Build
    name: MacOS Build
    os: osx

before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in travis_encrypted/id_rsa.enc -out travis_encrypted/id_rsa -d
- openssl aes-256-cbc -K $encrypted_b2704e9bbe4d_key -iv $encrypted_b2704e9bbe4d_iv
  -in travis_encrypted/id_rsa.pub.enc -out travis_encrypted/id_rsa.pub -d
- chmod 0400 travis_encrypted/id_rsa{,.pub}
- mv travis_encrypted/id_rsa{,.pub} ${HOME}/.ssh/

install: cargo build --release --verbose

script: cargo test --release --verbose --lib

before_deploy:
- pushd target/release
- tar -czvf "bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz" "bitbucket_server_cli"
- shasum -a 256 "bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz"
- popd

deploy:
  provider: releases
  token: "${GH_TOKEN}"
  file: target/release/bitbucket_server_cli-${TRAVIS_OS_NAME}.tar.gz
  name: Draft-travis-${TRAVIS_BUILD_NUMBER}
  skip_cleanup: true
  draft: true
  file_glob: true
  overwrite: false
  on:
    branch: master
    tags: false
