[package]
name = "bitbucket_server_cli"
version = "0.1.0"
authors = ["Jens Brimfors <jens.brimfors@gmail.se>"]
edition = "2018"

[dependencies]
serde = {version = "1.0.103", features = ["derive"]}
reqwest = "0.9.22"
generic_error = "0.1.0"
rayon = "1.2.1"
git2 = "0.11.0"
rpassword = "4.0.5"
indicatif = "0.14.0"
pickledb = "0.4.0"
dialoguer = "0.5.0"
