os: linux
dist: bionic
language: rust
cache:
  directories:
    - "$HOME/.cargo"
    - "$TRAVIS_BUILD_DIR/target"
before_cache:
  - rm -rf $HOME/.cargo/registry

before_install:
  - openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
    -in travis_encrypted/id_rsa.enc -out travis_encrypted/id_rsa -d
  - openssl aes-256-cbc -K $encrypted_b2704e9bbe4d_key -iv $encrypted_b2704e9bbe4d_iv
    -in travis_encrypted/id_rsa.pub.enc -out travis_encrypted/id_rsa.pub -d
  - chmod 0400 travis_encrypted/id_rsa{,.pub}
  - mv travis_encrypted/id_rsa{,.pub} ${HOME}/.ssh/
