name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --tests --bins --examples
    - name: Run tests
      run: cargo test --verbose --lib
    - name: Format
      run: cargo fmt --all -- --check
    - name: Bug hunt & best practice
      run: cargo clippy
