name: Rust audit

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  push:
    paths:
      - '**/Cargo.toml'
      - 'Cargo.lock'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
